name: openfeature
description: This is the Dart implementation of OpenFeature, a vendor-agnostic abstraction library for evaluating feature flags.
version: 0.0.1
repository: https://github.com/open-feature
homepage: https://openfeature.dev/
issue_tracker: https://github.com/open-feature
documentation: https://openfeature.dev/
publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
  collection: ^1.17.1
  coverage: ^1.6.3
