name: openfeature_dart
description: This is the Dart implementation of OpenFeature, a vendor-agnostic abstraction library for evaluating feature flags.
version: 0.0.1
repository: https://github.com/open-feature
homepage: https://openfeature.dev/
issue_tracker: https://github.com/open-feature
documentation: https://openfeature.dev/

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  http: ^0.13.0
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
